# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc419de10aeb3e41771f3cabcb1940ac662ce843cda8e77f2894bef154e1bab830a016b13e70a0732c58307d7914937ca1b5ac218b609c591faa41547f959479

test:
  secret_key_base: 4a912946c01944eee554e0155ec7be4bfed5896f61f16f4a44f78f11d5c7d47d3f96f5d3dd276947c7469f1494878eeb86567e1084ca4f3911fdf510bc88c216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
